"""Game services by type with language-specific activities."""

from .context_quiz_service import (
    ENGLISH_CONTEXT_QUIZ_ITEMS_BY_LEVEL,
    GAME_TYPE_CONTEXT_QUIZ,
    JAPANESE_CONTEXT_QUIZ_ITEMS_BY_LEVEL,
    ContextQuizAttempt,
    ContextQuizItem,
    ContextQuizOption,
    ContextQuizService,
)
from .game_service import GameActivity, GameService, InMemoryGameService
from .grammar_particle_fix_service import (
    GAME_TYPE_GRAMMAR_PARTICLE_FIX,
    JAPANESE_PARTICLE_ITEMS_BY_LEVEL,
    GrammarParticleAttempt,
    GrammarParticleFixService,
    GrammarParticleItem,
)
from .kanji_match_service import (
    GAME_TYPE_KANJI_MATCH,
    JAPANESE_KANJI_PAIRS_BY_LEVEL,
    WESTERN_ALPHABET_LANGUAGE_CODES,
    KanjiMatchAttempt,
    KanjiMatchService,
    KanjiPair,
)
from .listening_gap_fill_service import (
    ENGLISH_LISTENING_GAP_FILL_ITEMS_BY_LEVEL,
    GAME_TYPE_LISTENING_GAP_FILL,
    JAPANESE_LISTENING_GAP_FILL_ITEMS_BY_LEVEL,
    ListeningGapFillAttempt,
    ListeningGapFillItem,
    ListeningGapFillService,
)
from .pronunciation_match_service import (
    GAME_TYPE_PRONUNCIATION_MATCH,
    JAPANESE_PRONUNCIATION_PHRASES_BY_LEVEL,
    MATCH_THRESHOLD_BY_LEVEL,
    PronunciationMatchAttempt,
    PronunciationMatchService,
)
from .registry import GameServiceRegistry
from .script_speed_round_service import (
    ALIAS_GAME_TYPE_KANA_SPEED_ROUND,
    GAME_TYPE_SCRIPT_SPEED_ROUND,
    JAPANESE_KANA_BY_LEVEL,
    LATIN_CHARACTERS_BY_LEVEL,
    KanaSpeedRoundService,
    ScriptSpeedAttempt,
    ScriptSpeedRoundService,
)
from .sentence_order_service import (
    EASTERN_SCRIPT_LANGUAGE_CODES,
    ENGLISH_SENTENCE_ORDER_ITEMS_BY_LEVEL,
    GAME_TYPE_SENTENCE_ORDER,
    JAPANESE_SENTENCE_ORDER_ITEMS_BY_LEVEL,
    SentenceOrderAttempt,
    SentenceOrderItem,
    SentenceOrderService,
)
from .shadowing_score_service import (
    GAME_TYPE_SHADOWING_SCORE,
    LANGUAGE_JAPANESE,
    JAPANESE_SHADOWING_PHRASES_BY_LEVEL,
    JAPANESE_TARGET_CHARS_PER_SECOND_BY_LEVEL,
    ShadowingAttempt,
    ShadowingScoreService,
)

__all__ = [
    "GameActivity",
    "GameService",
    "InMemoryGameService",
    "GameServiceRegistry",
    "ContextQuizOption",
    "ContextQuizItem",
    "ContextQuizAttempt",
    "ContextQuizService",
    "GAME_TYPE_CONTEXT_QUIZ",
    "JAPANESE_CONTEXT_QUIZ_ITEMS_BY_LEVEL",
    "ENGLISH_CONTEXT_QUIZ_ITEMS_BY_LEVEL",
    "GrammarParticleItem",
    "GrammarParticleAttempt",
    "GrammarParticleFixService",
    "GAME_TYPE_GRAMMAR_PARTICLE_FIX",
    "JAPANESE_PARTICLE_ITEMS_BY_LEVEL",
    "KanjiPair",
    "KanjiMatchAttempt",
    "KanjiMatchService",
    "GAME_TYPE_KANJI_MATCH",
    "JAPANESE_KANJI_PAIRS_BY_LEVEL",
    "WESTERN_ALPHABET_LANGUAGE_CODES",
    "ListeningGapFillItem",
    "ListeningGapFillAttempt",
    "ListeningGapFillService",
    "GAME_TYPE_LISTENING_GAP_FILL",
    "JAPANESE_LISTENING_GAP_FILL_ITEMS_BY_LEVEL",
    "ENGLISH_LISTENING_GAP_FILL_ITEMS_BY_LEVEL",
    "PronunciationMatchAttempt",
    "PronunciationMatchService",
    "GAME_TYPE_PRONUNCIATION_MATCH",
    "JAPANESE_PRONUNCIATION_PHRASES_BY_LEVEL",
    "MATCH_THRESHOLD_BY_LEVEL",
    "ScriptSpeedAttempt",
    "ScriptSpeedRoundService",
    "KanaSpeedRoundService",
    "GAME_TYPE_SCRIPT_SPEED_ROUND",
    "ALIAS_GAME_TYPE_KANA_SPEED_ROUND",
    "JAPANESE_KANA_BY_LEVEL",
    "LATIN_CHARACTERS_BY_LEVEL",
    "SentenceOrderItem",
    "SentenceOrderAttempt",
    "SentenceOrderService",
    "GAME_TYPE_SENTENCE_ORDER",
    "EASTERN_SCRIPT_LANGUAGE_CODES",
    "JAPANESE_SENTENCE_ORDER_ITEMS_BY_LEVEL",
    "ENGLISH_SENTENCE_ORDER_ITEMS_BY_LEVEL",
    "ShadowingAttempt",
    "ShadowingScoreService",
    "GAME_TYPE_SHADOWING_SCORE",
    "LANGUAGE_JAPANESE",
    "JAPANESE_SHADOWING_PHRASES_BY_LEVEL",
    "JAPANESE_TARGET_CHARS_PER_SECOND_BY_LEVEL",
]
